pipeline {
    agent any

    environment {
        SONARQUBE_TOKEN = credentials('sonarqube-token')
        SNYK_TOKEN = credentials('snyk-token')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Linting') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                    sh 'npm install snyk'
                    sh 'npx snyk auth $SNYK_TOKEN'
                    sh 'npx snyk test --all-projects'
                }
            }
        }

        stage('Test') {
            steps {
                dir('frontend') {
                    sh 'npm test -- --watchAll=false'
                }
            }
        }

        stage('Build') {
            steps {
                dir('frontend') {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKERHUB_CREDENTIALS_USR', passwordVariable: 'DOCKERHUB_CREDENTIALS_PSW')]) {
                        sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                        sh 'docker build -t $DOCKERHUB_CREDENTIALS_USR/jenkins-secret-notes-frontend .'
                        sh 'docker push $DOCKERHUB_CREDENTIALS_USR/jenkins-secret-notes-frontend'
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKERHUB_CREDENTIALS_USR', passwordVariable: 'DOCKERHUB_CREDENTIALS_PSW')]) {
                    sshagent(['ec2-ssh-key']) {
                        sh '''
                        ssh -o StrictHostKeyChecking=no ubuntu@18.204.164.224 "
                            docker login -u $DOCKERHUB_CREDENTIALS_USR -p $DOCKERHUB_CREDENTIALS_PSW
                            docker network create secret-notes-jenkins-network || true
                            docker rm -f jenkins-secret-notes-frontend || true
                            docker pull $DOCKERHUB_CREDENTIALS_USR/jenkins-secret-notes-frontend
                            docker run -d --name jenkins-secret-notes-frontend --network secret-notes-jenkins-network -e NODE_ENV=production -p 8081:80 $DOCKERHUB_CREDENTIALS_USR/jenkins-secret-notes-frontend
                        "
                        '''
                    }
                }
            }
        }
    }
}
