services:
  db:
    image: postgres:16-alpine
    container_name: secret-notes-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: secret_notes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: secret-notes-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/secret_notes
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: secret-notes-frontend
    restart: unless-stopped
    ports:
      - "8080:80"

volumes:
  pgdata:
