name: Frontend CI/CD

on:
  push:
    branches:
      - main
      - deploy/production

jobs:
  build-deliver-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/secret-notes-frontend:latest

      #- name: Deploy to EC2
       # uses: appleboy/ssh-action@v0.1.7
        #with:
         # host: ${{ secrets.EC2_HOST }}
          #username: ubuntu
          #key: ${{ secrets.EC2_SSH_KEY }}
          #script: |
           # cd ~/your-app-folder
           # docker pull ${{ secrets.DOCKERHUB_USERNAME }}/secret-notes-frontend:latest
           # docker stop secret-notes-frontend || true
            #docker rm secret-notes-frontend || true
            #docker run -d --name secret-notes-frontend -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/secret-notes-frontend:latest
