name: Frontend CI/CD

on:
  workflow_run:
    workflows: ["Backend CI/CD"]
    types: [completed]
  push:
    branches:
      - deploy

jobs:
  build-deliver-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/secret-notes-frontend:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 54.210.250.141
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Create Docker network if not exists
            docker network create secret-notes-network || true

            # Stop and remove old containers
            docker rm -f secret-notes-frontend || true

            # Pull latest image
            docker pull azbraa/secret-notes-frontend:latest

            # Run frontend container
            docker run -d \
              --name secret-notes-frontend \
              --network secret-notes-network \
              -p 8080:80 \
              azbraa/secret-notes-frontend:latest
