name: Frontend CI/CD

on:
  workflow_run:
    workflows: ["Backend CI/CD"]
    types: [completed]
  push:
    branches:
      - deploy

jobs:
  build-deliver-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: http://18.204.164.224:9000
        with:
          projectBaseDir: ./frontend
          args: >
            -Dsonar.projectKey=secret-notes-frontend



      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/secret-notes-frontend:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 18.204.164.224
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker network create secret-notes-network || true
            docker rm -f secret-notes-frontend || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/secret-notes-frontend:latest
            docker run -d \
              --name secret-notes-frontend \
              --network secret-notes-network \
              -e NODE_ENV=production \
              -p 8080:80 \
              ${{ secrets.DOCKERHUB_USERNAME }}/secret-notes-frontend:latest
